export const services = [
  // ... your service data ...
{ id: "Advisory", title: "Strategic IT Advisory", description: "Maximize your ROI with our strategic Advisory service. We help you modernize systems and streamline operations for greater efficiency. Get expert guidance on governance and risk management to secure your assets and drive measurable business value.", short: "IT Advisory" },
  { id: "Agile", title: "Agile Product Development", description: "Accelerate success with our professional Agile Project Management consulting. We specialize in implementing effective Agile practices that increase transparency and stakeholder satisfaction. Get measurable results and a clear path to sustainable growth.", short: "React, Node, APIs" },
  { id: "ERP", title: "ERP Integration & Implementation", description: "Drive business transformation and competitive advantage with expert ERP implementation. We unify your core systems for a single, real-time source of truth, eliminating manual tasks and operational silos. This empowers data-driven decisions and accelerated growth.",short: "ERP" },
  { id: "Cybersecurity", title: "Cybersecurity", description: "Protect your business from top cybersecurity risks with expert Privileged Access Management. Our CyberArk specialists design and optimize tailored PAM solutions to strengthen security, enable Zero Trust, and prevent data breaches.",short: "Cybersecurity" },
{ id: "QualityEngineering", title: "Quality Engineering", description: "Move beyond basic testing to true Quality Engineering. We blend strategic QA consulting with robust test automation to identify and resolve defects early. Guarantee exceptional user experiences, reduce post-release risk, and ensure your application quality is built-in, not tested-in.",short: "QualityEngineering" },
{ id: "WebsiteDevelopment", title: "Website Development", description: "Build a powerful online presence with our custom website development services. We create responsive, user-friendly, and visually engaging websites that reflect your brand and drive business growth.",short: "Website Development" },
{ id: "Custom API Integration", title: "Custom API Integration", description: "Seamlessly connect your applications with our tailored API integration services. We streamline data flow, enhance system interoperability, and improve efficiency across your digital ecosystem.",short: "Custom API Integration" },
{ id: "Cloud Strategy & Transformation", title: "Cloud Strategy & Transformation", description: "Accelerate your digital journey with a well-defined cloud strategy. We help you plan, migrate, and optimize cloud solutions to enhance scalability, reduce costs, and drive innovation.",short: "Cloud Strategy & Transformation" },

];